### ISSUE TITLE
Doesn't work with stable due to feature flags `alloc` and `test`

### ISSUE THREAD

**Issue by rotty** [hroi/treebitmap#1]
Due to the use of the `alloc` and `test` feature flags, `treebitmap` only works on nightly. I think the parts of the test suite that rely on unstable features could simple be made optional, and having those parts run only on builds using the nightly compiler. I'll try to come up with a PR to achieve that.

I still have to research on how would one avoid the use of the `alloc` feature flag on stable Rust.

**Comment by hroi** [comment]
Sounds good! FYI, there is a bencher crate now on crates.io that works on stable.

It does not look like ``alloc``/``RawVec`` will be stable any time soon, or ever. It should not be too hard to remove that dependency and replacing the functionality by building on ``Vec::with_capacity`` in combination with ``mem::forget()``, alternatively only supporting ``T: Copy``.
