### ISSUE TITLE
Option to combine Ipv4Addr and Ipv6Addr into a single IpAddr table.

### ISSUE THREAD

**Issue by pusateri** [hroi/treebitmap#10]
Often, it would be nice to not have to decompose IpAddr into Ipv4Addr or Ipv6Addr and carry around two separate tables:
```
let mut v4_ifs = treebitmap::IpLookupTable::new();
let mut v6_ifs = treebitmap::IpLookupTable::new();

match ip {
    IpAddr::V4(ip4) => v4_ifs.insert(ip4, plen.into(), intf),
    IpAddr::V6(ip6) => v6_ifs.insert(ip6, plen.into(), intf),
};
```

Currently, this is required because of the type definitions of treebitmap:
```
treebitmap::IpLookupTable<Ipv4Addr, IfState>
treebitmap::IpLookupTable<Ipv6Addr, IfState>
```
But if instead, the tree definition was:
```
treebitmap::IpLookupTable<IpAddr, IfState>
```
We could use the same table for both where they can happily co-exist.

**Comment by hroi** [comment]
You can already do this: Use `IPv4Addr::to_ipv6_mapped()` and `Ipv6Addr::to_ipv4()`.

**Comment by pusateri** [comment]
I think you misunderstand what I mean. There would be no need to add additional bytes to an IPv4 address to make it the same length as an IPv6 address. I am talking about prefixes and prefix lengths. Not host addresses.
In a tree, 128.109/16 and 2001::1900:3001/48 can exist in the same table.
