### ISSUE TITLE
Save/Cache a tree for reuse?

### ISSUE THREAD

**Issue by jacktuck** [hroi/treebitmap#19]
It takes a few seconds to insert a ~5 million ips. But i know these ips at compile time and they will not change. Would/could it be possible to avoid doing 5 million inserts and somehow load the tree from a file for example?

(I'm new to rust. No idea what's possible or not!) :)

**Comment by pusateri** [comment]
This seems unlikely. Profiling and optimizing the insert code seems more likely from my limited knowledge.

**Comment by pusateri** [comment]
I have also seen degenerate cases based on the order of the prefixes inserted. Have you tried, sorting, reverse sorting, scrambling, randomizing the prefixes and see if that changes the insert time?

**Comment by jacktuck** [comment]
I think you're right. I'll look into other solutions.
