### ISSUE TITLE
Consider making the Address trait publically accessible

### ISSUE THREAD

**Issue by raphaelcohn** [hroi/treebitmap#8]
The Address trait is public but it's in a private module, so it can't be used from outside the crate. This limits IpLookupTable to only working with Ipv4Addr or Ipv6Addr, and it also prevents using the Address trait as a constraint. Additionally, the address trait does not constrain the struct data type; this is more a matter of style. This means I can construct an instance of IpLookupTable but never be able to use any methods on it...

For example, I'm working with several address-like objects that are byte-compatible with Ipv4Addr, but implement a different trait. I can't make my trait different trait 'depend on' Address (`trait MyTrait: Address`). Nor can I wrap IpLookupTable in a generic struct which works with either Ipv4 or Ipv6 addresses.

Please consider this change. It's two lines... (:-)

**Comment by hroi** [comment]
Fixed in #12

**Comment by raphaelcohn** [comment]
Ta
